# Generated by Django 5.2 on 2025-05-13 02:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_vendedor_ordencompracliente_itemordencompracliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPrecios',
            fields=[
                ('articulo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='articulo_lista', serialize=False, to='core.articulo')),
                ('precio_1', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_2', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_3', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_4', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'lista_precios',
            },
        ),
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('tipo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1)),
            ],
            options={
                'db_table': 'tipos_identificacion',
                'ordering': ['nombre_tipo'],
            },
        ),
        migrations.AlterModelOptions(
            name='articulo',
            options={'ordering': ['codigo_articulo']},
        ),
        migrations.AlterModelOptions(
            name='canalcliente',
            options={'ordering': ['nombre_canal']},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nro_identificacion']},
        ),
        migrations.AlterModelOptions(
            name='grupoarticulo',
            options={'ordering': ['codigo_grupo']},
        ),
        migrations.AlterModelOptions(
            name='lineaarticulo',
            options={'ordering': ['codigo_linea']},
        ),
        migrations.AlterModelOptions(
            name='ordencompracliente',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['nro_pedido']},
        ),
        migrations.AlterModelOptions(
            name='vendedor',
            options={'ordering': ['nombre']},
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='canal_id',
            new_name='canal',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='articulo_id',
            new_name='articulo',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='cliente_id',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='vendedor',
            old_name='nombres',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='canalcliente',
            name='id',
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='grupo_articulo', to='core.grupoarticulo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='presentacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='canalcliente',
            name='canal_id',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_item', to='core.pedido'),
        ),
        migrations.AlterField(
            model_name='ordencompracliente',
            name='nro_pedido',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ordencompracliente',
            name='pedido_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterModelTable(
            name='articulo',
            table='articulos',
        ),
        migrations.AlterModelTable(
            name='canalcliente',
            table='canal_cliente',
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='clientes',
        ),
        migrations.AlterModelTable(
            name='grupoarticulo',
            table='grupos_articulos',
        ),
        migrations.AlterModelTable(
            name='itemordencompracliente',
            table='items_ordenes_compra_cliente',
        ),
        migrations.AlterModelTable(
            name='itempedido',
            table='items_pedido',
        ),
        migrations.AlterModelTable(
            name='lineaarticulo',
            table='lineas_articulos',
        ),
        migrations.AlterModelTable(
            name='ordencompracliente',
            table='ordenes_compra_cliente',
        ),
        migrations.AlterModelTable(
            name='pedido',
            table='pedidos',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_identificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='clientes_tipo_identificacion', to='core.tipoidentificacion'),
        ),
        migrations.DeleteModel(
            name='ListaPrecio',
        ),
    ]
