# Generated by Django 5.2 on 2025-05-13 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_listaprecios_tipoidentificacion_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articulo',
            table='articulo',
        ),
    ]
