# Generated by Django 5.2 on 2025-05-13 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_articulo_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articulo',
            table='articulos',
        ),
    ]
